repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.3.3
  hooks:
    - id: sqlfluff-lint
      args: ["--dialect", "duckdb"] 
      files: \.sql$
      additional_dependencies:
        - sqlfluff-templater-dbt
        - dbt-core
        - dbt-duckdb
    - id: sqlfluff-fix
      args: ["--dialect", "duckdb"]
      files: \.sql$
      additional_dependencies:
        - sqlfluff-templater-dbt
        - dbt-core
        - dbt-duckdb