up:
	@docker compose --profile flower up -d

down:
	@docker compose --profile flower down -v

astro-start:
	@astro dev start

astro-stop:
	@astro dev stop

astro-restart:
	@astro dev restart

astro-init:
	@astro dev init astro-project
