version: 2

seeds:
  - name: product
    config:
      full_refresh: True
      database: retail_analytics
      schema: product
      column_types:
        id: integer
        subcategory_id: integer
        sku_no: varchar
        name: varchar
        color: varchar
        cost_price: numeric
        list_price: numeric
        weight: numeric
        class: varchar
        product_line: varchar
        stock_level: smallint
        reorder_threshold: smallint
        created_date: timestamp
        modified_date: timestamp
